DJPR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('NewsPaper.urls')),
]

NewsPaper/urls.py
from django.urls import path
from .views import PostsList, PostDetail

urlpatterns = [
   path('', PostsList.as_view()),
   path('<int:pk>/', PostDetail.as_view()),
]

NewsPaper/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.IntegerField(default=0)

    def update_rating(self):
        author_posts_rating = Post.objects.all().filter(author_id=self.pk).aggregate(
            posts_rating_sum=Sum('rating') * 3)
        author_comments_rating = Comment.objects.all().filter(user_id=self.user).aggregate(
            comments_rating_sum=Sum('rating_com'))

        print(author_posts_rating)
        print(author_comments_rating)

        self.author_rating = author_posts_rating['posts_rating_sum'] + author_comments_rating['comments_rating_sum']
        self.save()


class Category(models.Model):
    name_category = models.CharField(max_length=40, unique=True)


class Post(models.Model):
    ART = 'С'
    NEWS = 'Н'

    TYPES = [(ART, 'Статья'), (NEWS, 'Новость')]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=15, choices=TYPES)
    time_create = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField(Category)
    title = models.CharField(max_length=120)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:125] + '...'


class PostCategory(models.Model):
    category_PostCategory = models.ManyToManyField(Category)
    post_PostCategory = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=255)
    created_com = models.DateTimeField(auto_now_add=True)
    rating_com = models.IntegerField(default=0)

    def like(self):
        self.rating_com += 1
        self.save()

    def dislike(self):
        self.rating_com -= 1
        self.save()


NewsPaper/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import *

class PostsList(ListView):
    model = Post
    ordering = 'title'
    template_name = 'news.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'post'

templates/new.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
{% if post %}
        <table>
           <tr>
                <td><b>Название</b></td>
                <td><b>Текст</b></td>
                <td><b>Дата загрузки</b></td>
            </tr>
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.text|censor }}</td>
                <td>{{ post.time_create|date:'d M Y' }}</td>
            </tr>
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
{% endblock content %}

templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h2>Всего новостей: {{ object_list|length }}</h2>
    {% if posts %}
        <table>
            <tr>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Публикация</b></td>
                <td><b>Тип публикации</b></td>

            </tr>

            {% for post in posts %}
            <tr>
                <td>{{ post.title|truncatechars:50|censor }}</td>
                <td>{{ post.time_create|date:'d M Y' }}</td>
                <td>{{ post.text|truncatechars:50|censor }}</td>
                <td>{{ post.get_post_type_display }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}